#!/bin/bash
function config
{
	echo " ## INSTALLATION DE LA CONFIGURATION EMACS"
	cp -R ./assets/.emacs ~/.emacs
	mkdir -p ~/.emacs
	mkdir -p ~/.emacs/epitech/
	cp -R ./assets/.emacs/epitech/std_comment.el ~/.emacs.d/epitech/std_comment.el
	echo "Done"
	echo ""
}